### ISSUE TITLE
Issues converting files generated in scanning mode

### ISSUE THREAD

**Issue by saveriogzz** [actris-cloudnet/rpgpy#10]
Hello,

Jose @jdiasn, a Post Doc at TU Delft, has experienced some issues while converting files generated by a 94GHz RPG radar in **scanning mode**.

The errors are different, e.g. `input operand has more dimensions than allowed by the axis remapping`, `Arrays are not equal`, ecc..

I attach here a [summary of the errors](https://github.com/actris-cloudnet/rpgpy/files/7175753/rpg2nc_error_type.pdf), please let me know if you want me to also attach the files here or you prefer a different sharing method.

**Comment by tukiains** [comment]
Hi, if you can send me one file (or link to it) that does not work I can try to see what's going on there..

**Comment by saveriogzz** [comment]
Thanks Simo! The link is it [here](https://surfdrive.surf.nl/files/index.php/s/7V79AciAZQqmoFN).

I made a mistake in the issue above though: these files are coming from the RPG 35GHz. However, the very same issues are encountered with the ones produced by the 94GHz (the two are coupled).

**Comment by tukiains** [comment]
Did I get it right, these problems occur only occasionally and not with every file? As far as I can tell, by looking at those example files, the problems are due to weird / unexpected timestamps. Currently the converter just crashes if there are:
- Only one timestamp (profile) in the file. Not sure if this case can be fixed easily.
- Timestamps from different days. This can be fixed but there are several possible ways to deal with this.
- Timestamps with zero values (very strange..)

**Comment by saveriogzz** [comment]
> Did I get it right, these problems occur only occasionally and not with every file?

Correct.

I just saw #11 . Thanks for PR #12 ; Was this issue possibly fix by it?
@jdiasn can probably give more details here too.

**Comment by tukiains** [comment]
Looks more like a problem in the data - not in the reader. I'm closing this one for now.
